---

version: 0.0.1
metadata:
  name: Hacker News api test
  description: E2E test of the hacker news public api
environments:
  - name: production
    default: true
    plugins:
      - name: restqapi
        config:
          url: https://hacker-news.firebaseio.com
    outputs:
      - type: file
        enabled: true
        config:
          path: 'hacker-news.report.json'
      - type: slack
        enabled: true
        config:
          url: !env-var SLACK_WEBHOOK_URL
          showErrors: true
