on: [push]

name: RestQa Example Testing

jobs:
  Test-Examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_folder:
          - hacker-news
    steps:
    - uses: actions/checkout@v2
    - name: Validate the gerkin files for ${{ matrix.example_folder }}
      uses: restqa/gherkin-linter-action@0.0.1
      with:
        path: ./${{ matrix.example_folder }}
        config_file:  ./.gherkin-lintrc
    - name: Run E2E Test Automation on the Environment for ${{ matrix.example_folder }}
      uses: restqa/restqa-action@0.0.1
      with:
        path: ./${{ matrix.example_folder }}
        
